### ISSUE TITLE
ghost image during transition

### ISSUE THREAD

**Issue by legluondunet** [emoose/sh2proxy#3]
Hello,

firstly I would like to thank you for your work, sh2proxy is actually the better solution to play this game with sound and stability for Linux users like me.

I found a little bug, during transition, I have this ghost image instead of a black screen:
https://lh4.googleusercontent.com/-LuHYqAs6lFI/VMbGm7CyO9I/AAAAAAAAAbA/P-0Sh0mM9O0/s1280/Capture%2520du%25202015-01-26%252022%253A58%253A18.jpg

Were you aware about this bug?

LGDN

**Comment by emoose** [comment]
Crap sorry for the late reply, saw this and meant to reply earlier but I got side tracked.

Someone else did mention this before but I didn't get to test much with them.

Have you tried messing with the transition settings in the ini and seeing if it fixes it? I'm guessing it must be something to do with my patch.

Also what's your PC's specs? I think this might be an AMD issue but I'm not sure.

**Comment by legluondunet** [comment]
My config: Ubuntu 14.04 LTS Trusty 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 331.113 - resolution 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM - WIne 1.7.35

**Comment by legluondunet** [comment]
My config: Ubuntu 14.04 LTS Trusty 64 bits - NVIDIA GeForce GTX 770 - official Ubuntu Nvidia drivers 331.113 - resolution 1920x1080 - Processor Intel i5-3570 3,4 Ghz - 8 Go RAM - WIne 1.7.35

I change some settings like transiton duration or transition resolution, change nothing, return to the default values (transition=1, transition resolution 0 0) and now I can not reproduce the bug...reboot computer, launch SH2, no more ghost image, I don't understand. You can close this bug.
