### ISSUE TITLE
Full Screen 4:3 under windows 10

### ISSUE THREAD

**Issue by DangusTaargus** [emoose/sh2proxy#9]
I'm not sure if you still check this, but with Windows 10 came the full screen with border issue, and it can be fixed by running the game at your screen's resolution as well as setting the game to -windowed -borderless. 

This does get rid of the border for me, however, I am the type of person that actually prefers to play these older games at their intended resolution, and don't actually mind setting it to something like 1440x1080 or 1280x1024 (both 4:3 resolutions). This allows me to play the game without stretched fmv's and menus. The only issue with this is that, under windows 10, to fix the border, the game will now run with my desktop visible in the background.

Is there anyway you can add a setting that scales the game to a certain aspect ratio, but that doesn't stretch the game? If no, that's understandable, I'm just not entirely familiar with the limitations of application wrappers.

What I am asking for worked prior to windows 10, so maybe that's the real issue. But I at least wanted to bring this up.

Thanks!

**Comment by zawarudo** [comment]
Came across this issue today so I've added a way to remove the borders even on fullscreen which seems to work fine on my end. Give it a try at your own risk.

https://mega.nz/#!dtVijD6a!DDZlIKL1ZsNNobXpEx4wlv6-j5CDV7yrHfpxoRaSSb8

It adds a new flag in sh2proxy.ini to force fullscreen no matter the window mode.

<pre>
# Force borderless even on fullscreen
ForceBorderless = 1
</pre>

**Comment by DangusTaargus** [comment]
Thanks for adding this, however I am having an issue with your change. When I try to launch i get 3 missing .dll system errors:
MSVCP140D.dll
ucrtbased.dll
VCRUNTIME140D.dll

These seem to be obviously related Visual C++ redistributable. But I downloaded everyhing on microsoft website and nothing fixes it. Considering I had no trouble with the previous d3d8.dll, perhaps you compiled it with a newer version than the original and something is different? Anything I can do to fix? or do you need to change something?

**Comment by zawarudo** [comment]
Hey, I indeed compiled it with the latest version of visual studio.
I'm unfamiliar with these tools so I'll look into it tonight.

You could try grabbing visual studio 2015 community edition from
https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx
and compiling it from my branch
https://github.com/zawarudo/sh2proxy/tree/fullscreen_border_fix

On Sun, Nov 8, 2015 at 9:39 PM, DangusTaargus <notifications@github.com>
wrote:

> Thanks for adding this, however I am having an issue with your change.
> When I try to launch i get 3 missing .dll system errors:
> MSVCP140D.dll
> ucrtbased.dll
> VCRUNTIME140D.dll
>
> These seem to be obviously related Visual C++ redistributable. But I
> downloaded everyhing on microsoft website and nothing fixes it. Considering
> I had no trouble with the previous d3d8.dll, perhaps you compiled it with a
> newer version than the original and something is different? Anything I can
> do to fix? or do you need to change something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emoose/sh2proxy/issues/9#issuecomment-154910726>.
>



-- 
Mihai Badescu

**Comment by zawarudo** [comment]
You can also just install the 2015 Redistributable here. Let me know if that works. If not I can download and recompile an earlier version for you.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by DangusTaargus** [comment]
I tried that already. It didn't change anything, but it interestingly enough doesn't show up among my installed programs...and yet, if I try to re-install it, I get the options to repair or uninstall... meaning it's definitely been installed.

I'll give it another go and see if maybe there's something else in my way.

**Comment by zawarudo** [comment]
Hey have you tried both x64 and x86 redist installers on that page?

**Comment by DangusTaargus** [comment]
I have. I even tried opening you're code and recompiling it myself... but that proved to be out of my depth (My coding experience is Java only). The community Visual Studio wouldn't load your project and the solution it was offering wasn't clear. If you think you can just compile it using the original 2013 version that was already recommended, I would be very thankful, as long as it's not a lot of work on your end.

I haven't tried moving the dll files because I figured I didn't have them at all. But I guess that's another thing to try.

For the record, I have fixed this problem through a workaround by using Borderless Gaming. So if you don't want to put any more trouble into this, I appreciate what you've already done and I am sure others will have more luck with your branch.

I tend to dislike having a slew of third party apps running at launch to fix problems, so while I would love to fix this with this proxy, I can live without it and check back later.

**Comment by zawarudo** [comment]
I recompiled them and gave you two to try. Good luck.

https://mega.nz/#!048nwCQD!3O7dStgMoc1ITTvoHCMyHwAXFsPf_sK0n0Ekve95q0E

**Comment by DangusTaargus** [comment]
So those don't work either... they report a missing msvcr120D.dll. I looked into it, and it seems a dll. with a D after the 120 or, in the previous version, a 140, means that the code is being compiled for debug, which means the end user with installed redists, even if they are the correct ones, still won't receive those debug .dll files, and will still get the error.

With the new ones you sent, I only get the single missing .dll error, so that's something!

I don't know enough about how you are compiling these... but I hope that helps. I can only imagine that any other user trying to use this branch is going to run into the same issues that I have.

**Comment by zawarudo** [comment]
You're right, should have been compiling for release build whoops.

Here you go
https://mega.nz/#!5kkF2DzB!KHyw9FXx2pzAF_7B-s9zS_89ESN5rnzV5w0QcB0OdS8

**Comment by DangusTaargus** [comment]
That did it!

I would recommend that you release that build! Thank you so much for all your effort.

I don't know if you follow this thread:
http://www.neogaf.com/forum/showthread.php?t=488899

But if you do or you have a neogaf account (I don't... can't start one with free email account), they would likely love to know about this as this is the biggest community of folks trying to preserve this game that I am aware of.

THANKS!
